//
//  QueryExecutionCoordinator+Helpers.swift
//  TablePro
//

import AppKit
import Foundation
import os
import TableProPluginKit

private let helpersLogger = Logger(subsystem: "com.TablePro", category: "QueryExecutionCoordinator")

extension QueryExecutionCoordinator {
    func resolveRowCap(sql: String, tabType: TabType, bypassLimit: Bool = false) -> Int? {
        guard !bypassLimit,
              let cap = QueryExecutor.resolveRowCap(
                  sql: sql, tabType: tabType, databaseType: parent.connection.type
              )
        else {
            return nil
        }
        guard !SQLLimitDetector.hasExplicitRowLimit(
            sql,
            autoLimitStyle: PluginManager.shared.autoLimitStyle(for: parent.connection.type),
            lexicalDialect: parent.sqlDialect
        ) else {
            return nil
        }
        return cap
    }

    func parseSchemaMetadata(_ schema: FetchedTableSchema) -> ParsedSchemaMetadata {
        QueryExecutor.parseSchemaMetadata(schema)
    }

    /// History belongs to the database the tab actually ran on, not to wherever the
    /// sidebar happens to point when the entry is written.
    func historyDatabaseName(tabId: UUID) -> String {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else {
            return parent.browseDatabaseName
        }
        return parent.scope(for: tab)?.database ?? parent.browseDatabaseName
    }

    func historySchemaName(tabId: UUID) -> String? {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else { return nil }
        return parent.scope(for: tab)?.schema
    }

    /// A table tab's SQL is generated by the app for browsing, paging, sorting and filtering.
    /// It is recorded so the user can audit what was sent, but it is not something they authored.
    func historySource(tabId: UUID) -> QueryHistorySource {
        guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else { return .editor }
        return tab.tabType == .table ? .tableBrowse : .editor
    }

    func isMetadataCached(tabId: UUID, tableName: String) -> Bool {
        guard let idx = parent.tabManager.tabs.firstIndex(where: { $0.id == tabId }) else {
            return false
        }
        let tab = parent.tabManager.tabs[idx]
        let tableRows = parent.tabSessionRegistry.tableRows(for: tab.id)
        let enumSetColumnNames: [String] = tableRows.columns.enumerated().compactMap { i, name in
            guard i < tableRows.columnTypes.count,
                  tableRows.columnTypes[i].isEnumType || tableRows.columnTypes[i].isSetType else { return nil }
            return name
        }
        let enumsReady = enumSetColumnNames.allSatisfy { tableRows.columnEnumValues[$0] != nil }
        let cached = tab.tableContext.tableName == tableName
            && !tableRows.columnDefaults.isEmpty
            && !tab.tableContext.primaryKeyColumns.isEmpty
            && tableRows.foreignKeysFetched
            && enumsReady
        helpersLogger.info(
            "[fk] cache check table=\(tableName, privacy: .public) defaults=\(tableRows.columnDefaults.count) pks=\(tab.tableContext.primaryKeyColumns.count) fkFetched=\(tableRows.foreignKeysFetched) fks=\(tableRows.columnForeignKeys.count) enumsReady=\(enumsReady) cached=\(cached)"
        )
        return cached
    }

    /// Deliberately does not set `foreignKeysFetched`. The prefetch answers which columns carry the
    /// arrow, which is all the first paint needs; defaults, primary keys, nullability and comments
    /// still come from the table's own metadata fetch, and claiming they had arrived would let
    /// `isMetadataCached` skip it.
    ///
    /// A miss starts the fetch for this scope, so the store refills itself after a schema refresh
    /// or a database switch cleared it. Only this table pays the wait; the next one is answered.
    private func prefetchedForeignKeys(tabIndex: Int, tableName: String) -> [String: ForeignKeyInfo]? {
        guard tabIndex < parent.tabManager.tabs.count,
              let scope = parent.scope(for: parent.tabManager.tabs[tabIndex])
        else { return nil }
        if let cached = SchemaForeignKeyStore.shared.foreignKeysByColumn(for: scope, table: tableName) {
            return cached
        }
        parent.prefetchForeignKeys(scope: scope)
        return nil
    }

    func applyPhase1Result( // swiftlint:disable:this function_parameter_count
        tabId: UUID,
        columns: [String],
        columnTypes: [ColumnType],
        rows: [[PluginCellValue]],
        executionTime: TimeInterval,
        rowsAffected: Int,
        statusMessage: String?,
        tableName: String?,
        isEditable: Bool,
        metadata: ParsedSchemaMetadata?,
        hasSchema: Bool,
        sql: String,
        connection conn: DatabaseConnection,
        isTruncated: Bool = false,
        queryParameterValues: [QueryParameter]? = nil,
        historySQL: String? = nil,
        anchor: StatementAnchor? = nil
    ) {
        guard let idx = parent.tabManager.tabs.firstIndex(where: { $0.id == tabId }) else { return }

        if let routed = ExplainResultRouter.route(
            sql: sql,
            columns: columns,
            rows: rows,
            databaseType: conn.type,
            declaredVariants: conn.type.explainVariants
        ) {
            applyExplainResult(
                tabId: tabId,
                routed: routed,
                executionTime: executionTime,
                rowCount: rows.count,
                sql: sql,
                historySQL: historySQL ?? sql,
                connection: conn,
                queryParameterValues: queryParameterValues,
                anchor: anchor
            )
            return
        }

        let existingTabId = parent.tabManager.tabs[idx].id
        var columnEnumValues: [String: [String]] = [:]
        var columnDefaults: [String: String?] = [:]
        var columnForeignKeys: [String: ForeignKeyInfo] = [:]
        var columnNullable: [String: Bool] = [:]
        var columnComments: [String: String] = [:]
        for (index, colType) in columnTypes.enumerated() {
            if case .enumType(_, let values) = colType, let vals = values, index < columns.count {
                columnEnumValues[columns[index]] = vals
            }
        }

        var foreignKeysFetched = false

        if let metadata {
            columnDefaults = metadata.columnDefaults
            columnForeignKeys = metadata.columnForeignKeys ?? [:]
            columnNullable = metadata.columnNullable
            columnComments = metadata.columnComments
            foreignKeysFetched = metadata.columnForeignKeys != nil
            for (col, vals) in metadata.columnEnumValues {
                columnEnumValues[col] = vals
            }
        } else {
            let existing = parent.tabSessionRegistry.tableRows(for: existingTabId)
            columnDefaults = existing.columnDefaults
            columnForeignKeys = existing.columnForeignKeys
            columnNullable = existing.columnNullable
            columnComments = existing.columnComments
            foreignKeysFetched = existing.foreignKeysFetched
            for (col, vals) in existing.columnEnumValues where columnEnumValues[col] == nil {
                columnEnumValues[col] = vals
            }
        }

        if columnForeignKeys.isEmpty, !foreignKeysFetched, let tableName {
            columnForeignKeys = prefetchedForeignKeys(tabIndex: idx, tableName: tableName) ?? [:]
        }

        let newTableRows = TableRows.from(
            queryRows: rows,
            columns: columns,
            columnTypes: columnTypes,
            columnDefaults: columnDefaults,
            columnForeignKeys: columnForeignKeys,
            columnEnumValues: columnEnumValues,
            columnNullable: columnNullable,
            columnComments: columnComments,
            foreignKeysFetched: foreignKeysFetched
        )
        let previousTableName = parent.tabManager.tabs[idx].tableContext.tableName
        parent.flushBufferToActiveResult(tabId: existingTabId, pinnedOnly: true)
        parent.setActiveTableRows(newTableRows, for: existingTabId)

        parent.tabManager.mutate(at: idx) { tab in
            tab.schemaVersion += 1
            tab.execution.executionTime = executionTime
            tab.execution.rowsAffected = rowsAffected
            tab.execution.statusMessage = statusMessage
            tab.execution.lastExecutedAt = Date()
            tab.tableContext.tableName = tableName
            tab.tableContext.isEditable = isEditable
            tab.pagination.isLoading = false

            if let metadata, let approxCount = metadata.approximateRowCount, approxCount > 0,
               !tab.filterState.hasAppliedFilters {
                tab.pagination.applyDerivedRowCount(approxCount, isApproximate: true)
            }
            if hasSchema {
                tab.metadataVersion += 1
            }

            let rs = ResultSet(
                label: ResultSet.label(tableName: tableName, anchor: anchor, index: 0),
                tableRows: newTableRows
            )
            rs.statementAnchor = anchor
            rs.executionTime = tab.execution.executionTime
            rs.rowsAffected = tab.execution.rowsAffected
            rs.statusMessage = tab.execution.statusMessage
            rs.isTruncated = isTruncated
            rs.baseQuery = sql

            tab.display.replaceUnpinnedResults(with: [rs])

            if isTruncated {
                tab.pagination.hasMoreRows = true
                tab.pagination.isLoadingMore = false
            } else {
                tab.pagination.resetLoadMore()
            }
            tab.pagination.setBaseQueryForMore(sql, parameterValues: nil)

            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        parent.toolbarState.isResultsCollapsed = false

        let resolvedPKs: [String]
        if let pks = metadata?.primaryKeyColumns, !pks.isEmpty {
            resolvedPKs = pks
        } else if let defaultPK = PluginManager.shared.defaultPrimaryKeyColumn(for: conn.type) {
            resolvedPKs = [defaultPK]
        } else if tableName == previousTableName {
            resolvedPKs = parent.tabManager.tabs[idx].tableContext.primaryKeyColumns
        } else {
            resolvedPKs = []
        }

        parent.tabManager.mutate(at: idx) { $0.tableContext.primaryKeyColumns = resolvedPKs }
        captureOrigin(
            tabIndex: idx,
            tabId: tabId,
            tableName: tableName,
            primaryKeyColumns: resolvedPKs,
            isEditable: isEditable
        )

        if parent.tabManager.selectedTabId == tabId {
            parent.changeManager.configureForTable(
                tableName: tableName ?? "",
                schemaName: parent.tabManager.tabs[idx].tableContext.schemaName,
                columns: columns,
                primaryKeyColumns: resolvedPKs,
                databaseType: conn.type
            )
        }

        recordHistory(
            QueryHistoryRecordRequest(
                query: historySQL ?? sql,
                connectionId: conn.id,
                databaseName: historyDatabaseName(tabId: tabId),
                databaseType: conn.type,
                schemaName: historySchemaName(tabId: tabId),
                source: historySource(tabId: tabId),
                executionTime: executionTime,
                rowCount: rows.count,
                wasSuccessful: true
            )
        )

        if parent.tabManager.selectedTabId == tabId, isEditable, !parent.changeManager.hasChanges {
            parent.changeManager.clearChangesAndUndoHistory()
        }
    }

    private func applyExplainResult(
        tabId: UUID,
        routed: ExplainResultRouter.RoutedPlan,
        executionTime: TimeInterval,
        rowCount: Int,
        sql: String,
        historySQL: String,
        connection conn: DatabaseConnection,
        queryParameterValues: [QueryParameter]?,
        anchor: StatementAnchor? = nil
    ) {
        let databaseName = historyDatabaseName(tabId: tabId)
        let schemaName = historySchemaName(tabId: tabId)
        let historyId = UUID()
        let captured = QueryPlanCaptureBuilder.make(
            subjectSQL: routed.subjectSQL,
            rawPlan: routed.rawText,
            format: routed.format,
            variantKey: routed.variantKey,
            scope: QueryPlanScope(
                connectionId: conn.id,
                databaseType: conn.type,
                databaseName: databaseName,
                schemaName: schemaName
            ),
            executionTime: executionTime,
            capturedAt: Date(),
            historyId: historyId,
            queryParameters: queryParameterValues
        )
        parent.flushBufferToActiveResult(tabId: tabId, pinnedOnly: true)
        parent.tabManager.mutate(tabId: tabId) { tab in
            tab.execution.executionTime = executionTime
            tab.execution.rowsAffected = 0
            tab.execution.statusMessage = nil
            tab.execution.lastExecutedAt = Date()
            tab.pagination.resetLoadMore()
            tab.display.replaceUnpinnedResults(
                with: [ExplainResultSetFactory.make(
                    rawText: routed.rawText,
                    plan: routed.plan,
                    sql: sql,
                    executionTime: executionTime,
                    anchor: anchor,
                    planContext: captured.context,
                    format: routed.format
                )]
            )
            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        parent.seedBufferFromActiveResult(tabId: tabId)
        parent.toolbarState.isResultsCollapsed = false

        recordHistory(
            QueryHistoryRecordRequest(
                id: historyId,
                query: historySQL,
                connectionId: conn.id,
                databaseName: databaseName,
                databaseType: conn.type,
                schemaName: schemaName,
                source: .explain,
                executionTime: executionTime,
                rowCount: rowCount,
                wasSuccessful: true,
                planCapture: captured.capture
            )
        )
    }

    func launchPhase2Work(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType,
        schemaTask: Task<FetchedTableSchema, Error>?
    ) {
        let isNonSQL = PluginManager.shared.editorLanguage(for: connectionType) != .sql
        let contentEpoch = parent.tabExecution.contentEpoch(for: tabId)
        let resultSetId = parent.tabManager.tabs.first { $0.id == tabId }?.display.activeResultSetId
        Task(priority: .utility) { [weak self, parent] in
            /// The caller marked the total pending when it committed to this phase. Every way out of
            /// here that does not reach `resolveRowCount` has to take that back, or the tab reports a
            /// count that is never coming and never offers `Count Exactly` again.
            guard let self else {
                parent.releaseCountPending(for: tabId)
                return
            }
            guard !parent.isTearingDown else { return }

            let schema = try? await schemaTask?.value
            if schemaTask != nil, schema == nil {
                helpersLogger.error("[fk] phase2 schema fetch failed or cancelled table=\(tableName, privacy: .public)")
            }

            await MainActor.run { [weak self] in
                guard let self else {
                    parent.releaseCountPending(for: tabId)
                    return
                }
                if let schema {
                    applySchemaMetadata(schema, tabId: tabId, tableName: tableName, resultSetId: resultSetId)
                }
                /// A retarget or a re-execution that overtook this one owns the tab's state now, and
                /// it raised its own pending mark. Clearing here would release the successor's.
                guard parent.tabExecution.isSameContent(contentEpoch, for: tabId) else { return }
                resolveRowCount(
                    tableName: tableName,
                    tabId: tabId,
                    connectionType: connectionType
                )
            }

            guard !isNonSQL, let schema else { return }

            let columnEnumValues = await parent.fetchEnumValues(
                columnInfo: schema.columns,
                tableName: tableName,
                connectionType: connectionType
            )
            guard !columnEnumValues.isEmpty else { return }

            await MainActor.run { [weak self] in
                guard let self, !Task.isCancelled else { return }
                applyEnumValues(columnEnumValues, tabId: tabId, tableName: tableName, resultSetId: resultSetId)
            }
        }
    }

    /// Stamps the active result with the table its rows came from.
    ///
    /// `QueryTab.tableContext` always describes the newest execution, so a result the user later
    /// clicks back to has to carry its own identity or an edit made on it is written against
    /// whatever ran last (#2243).
    func captureOrigin(
        tabIndex: Int,
        tabId: UUID,
        tableName: String?,
        primaryKeyColumns: [String],
        isEditable: Bool
    ) {
        guard tabIndex < parent.tabManager.tabs.count else { return }
        let context = parent.tabManager.tabs[tabIndex].tableContext
        parent.tabManager.tabs[tabIndex].display.activeResultSet?.origin = ResultOrigin(
            tableName: tableName,
            schemaName: context.schemaName,
            databaseName: historyDatabaseName(tabId: tabId),
            primaryKeyColumns: primaryKeyColumns,
            isEditable: isEditable,
            isView: context.isView,
            keysResolved: true
        )
    }

    /// Phase-2 metadata belongs to the result its fetch was launched for, not to whatever the tab
    /// happens to be showing when it lands. A query tab can hold several results and the user can
    /// switch between them while the schema round trips, so keying on the tab's current table name
    /// paints one table's foreign keys, defaults and primary keys onto another table's rows.
    private func resultStillActive(_ tabId: UUID, _ resultSetId: UUID?) -> Bool {
        parent.tabManager.tabs.contains { $0.id == tabId && $0.display.activeResultSetId == resultSetId }
    }

    private func isActiveTab(_ tabId: UUID) -> Bool {
        guard let activeIdx = parent.tabManager.selectedTabIndex,
              activeIdx < parent.tabManager.tabs.count else { return false }
        return parent.tabManager.tabs[activeIdx].id == tabId
    }

    private func applySchemaMetadata(
        _ schema: FetchedTableSchema,
        tabId: UUID,
        tableName: String,
        resultSetId: UUID?
    ) {
        guard resultStillActive(tabId, resultSetId) else {
            helpersLogger.info("[fk] phase2 apply skipped, tab closed or table changed table=\(tableName, privacy: .public)")
            return
        }
        applyPhase2Metadata(parsed: QueryExecutor.parseSchemaMetadata(schema), tabId: tabId)
    }

    private func applyEnumValues(
        _ values: [String: [String]],
        tabId: UUID,
        tableName: String,
        resultSetId: UUID?
    ) {
        guard resultStillActive(tabId, resultSetId) else { return }
        let existing = parent.tabSessionRegistry.tableRows(for: tabId)
        let hasNewValues = values.contains { key, value in
            existing.columnEnumValues[key] != value
        }
        guard hasNewValues else { return }

        parent.mutateActiveTableRows(for: tabId) { rows in
            for (col, vals) in values {
                rows.columnEnumValues[col] = vals
            }
            return .columnsReplaced
        }
        parent.tabManager.mutate(tabId: tabId) { $0.metadataVersion += 1 }
        if isActiveTab(tabId) {
            parent.dataTabDelegate?.tableViewCoordinator?.refreshCellPresentations()
        }
    }

    private func applyPhase2Metadata(parsed: ParsedSchemaMetadata, tabId: UUID) {
        guard parent.tabManager.tabs.contains(where: { $0.id == tabId }) else { return }

        parent.mutateActiveTableRows(for: tabId) { rows in
            rows.updateDisplayMetadata(
                columnDefaults: parsed.columnDefaults,
                columnForeignKeys: parsed.columnForeignKeys,
                columnNullable: parsed.columnNullable,
                columnComments: parsed.columnComments
            )
        }

        parent.tabManager.mutate(tabId: tabId) { tab in
            if !parsed.primaryKeyColumns.isEmpty {
                tab.tableContext.primaryKeyColumns = parsed.primaryKeyColumns
                tab.display.activeResultSet?.origin?.primaryKeyColumns = parsed.primaryKeyColumns
                tab.display.activeResultSet?.origin?.keysResolved = true
            }
            if let approxCount = parsed.approximateRowCount, approxCount > 0,
               !tab.filterState.hasAppliedFilters {
                tab.pagination.applyDerivedRowCount(approxCount, isApproximate: true)
            }
            tab.metadataVersion += 1
        }

        if parent.tabManager.selectedTabId == tabId, !parsed.primaryKeyColumns.isEmpty {
            parent.changeManager.setPrimaryKeyColumns(parsed.primaryKeyColumns)
        }

        if parent.tabManager.selectedTabId == tabId {
            parent.changeManager.setGeneratedColumns(parsed.generatedColumns)
        }

        let refreshed = isActiveTab(tabId)
        if refreshed {
            parent.dataTabDelegate?.tableViewCoordinator?.refreshCellPresentations()
        }
        helpersLogger.info(
            "[fk] phase2 applied tab=\(tabId, privacy: .public) fks=\(parsed.columnForeignKeys?.count ?? -1) defaults=\(parsed.columnDefaults.count) activeTabRefreshed=\(refreshed)"
        )
    }

    func launchPhase2Count(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType
    ) {
        resolveRowCount(
            tableName: tableName,
            tabId: tabId,
            connectionType: connectionType
        )
    }

    /// Validates against the tab's content identity, not the execution claim. The claim is settled
    /// the moment phase 1 is applied, which happens before phase 2 is even dispatched, so a claim
    /// check here is false on every run and the count never lands.
    func resolveRowCount(
        tableName: String,
        tabId: UUID,
        connectionType: DatabaseType
    ) {
        let isNonSQL = PluginManager.shared.editorLanguage(for: connectionType) != .sql
        let contentEpoch = parent.tabExecution.contentEpoch(for: tabId)
        let token = UUID()

        parent.tabManager.mutate(tabId: tabId) { $0.pagination.isCountPending = true }

        let task = Task(priority: .utility) { [weak self, parent] in
            guard let self else { return }
            guard !parent.isTearingDown else { return }

            let prepared: (plan: RowCountPlan, sql: String?, scope: DatabaseScope?) = await MainActor.run {
                guard let tab = parent.tabManager.tabs.first(where: { $0.id == tabId }) else {
                    return (.skip, nil, nil)
                }
                let scope = parent.scope(for: tab)
                let plan = Self.rowCountPlan(
                    isNonSQL: isNonSQL,
                    filterState: tab.filterState,
                    approximateRowCount: tab.pagination.totalRowCount,
                    threshold: AppSettingsManager.shared.dataGrid.countRowsIfEstimateLessThan
                )
                guard case let .exactCount(filtered) = plan else { return (plan, nil, scope) }
                let buffer = parent.tabSessionRegistry.tableRows(for: tabId)
                let sql = parent.queryBuilder.buildFilteredCountQuery(
                    tableName: tableName,
                    schemaName: tab.tableContext.schemaName,
                    filters: filtered ? tab.filterState.appliedFilters : [],
                    logicMode: tab.filterState.filterLogicMode,
                    columns: buffer.columns,
                    columnTypes: buffer.columnTypes
                )
                return (plan, sql, scope)
            }

            let outcome = await Self.rowCountOutcome(
                plan: prepared.plan,
                sql: prepared.sql,
                scope: prepared.scope,
                tableName: tableName
            )

            await MainActor.run {
                /// The flag says a count is running, so it has to clear on every way out, including
                /// the ones that apply nothing. Only the task that still owns the slot may clear it,
                /// or a superseded task would release the successor that replaced it.
                let ownsCount = parent.clearRowCountTask(for: tabId, token: token)
                let isCurrent = parent.tabExecution.isSameContent(contentEpoch, for: tabId)
                parent.tabManager.mutate(tabId: tabId) { tab in
                    if ownsCount {
                        tab.pagination.isCountPending = false
                    }
                    guard isCurrent, let applied = outcome?.appliedTotal else { return }
                    tab.pagination.applyDerivedRowCount(applied.total, isApproximate: applied.isApproximate)
                }
            }
        }
        parent.setRowCountTask(task, token: token, for: tabId)
    }

    /// Runs the plan the caller resolved. Split out so `resolveRowCount` has one exit that clears
    /// `isCountPending`, rather than an early return per plan that leaves it set.
    private static func rowCountOutcome(
        plan: RowCountPlan,
        sql: String?,
        scope: DatabaseScope?,
        tableName: String
    ) async -> RowCountOutcome? {
        guard let scope else { return nil }

        switch plan {
        case .skip:
            return nil
        case .clear:
            return .clear
        case .approximate:
            guard let count = try? await DatabaseManager.shared.withMetadataDriver(scope: scope, { driver in
                try await driver.fetchApproximateRowCount(table: tableName)
            }) else { return nil }
            return .count(count, isApproximate: true)
        case let .filteredNonSQL(filters, logicMode):
            guard let count = try? await DatabaseManager.shared.withMetadataDriver(scope: scope, workload: .bulk, { driver in
                try await driver.fetchFilteredRowCount(table: tableName, filters: filters, logicMode: logicMode)
            }) else { return .clear }
            return .count(count, isApproximate: false)
        case .exactCount:
            guard let sql else { return nil }
            do {
                let count = try await DatabaseManager.shared.withMetadataDriver(scope: scope, workload: .bulk) { driver in
                    let result = try await driver.execute(query: sql)
                    guard let countStr = result.rows.first?.first?.asText else { return Int?.none }
                    return Int(countStr)
                }
                return count.map { RowCountOutcome.count($0, isApproximate: false) }
            } catch {
                helpersLogger.warning("COUNT query failed for \(tableName): \(error.localizedDescription)")
                return nil
            }
        }
    }

    static func rowCountPlan(
        isNonSQL: Bool,
        filterState: TabFilterState,
        approximateRowCount: Int?,
        threshold: Int
    ) -> RowCountPlan {
        if isNonSQL {
            return filterState.hasAppliedFilters
                ? .filteredNonSQL(filters: filterState.appliedFilters, logicMode: filterState.filterLogicMode)
                : .approximate
        }
        let exceedsThreshold = (approximateRowCount ?? 0) >= threshold
        if filterState.hasAppliedFilters {
            return exceedsThreshold ? .clear : .exactCount(filtered: true)
        }
        return exceedsThreshold ? .skip : .exactCount(filtered: false)
    }

    /// Reports a failure that belongs to this tab. Ownership of the window's task handle and the
    /// spinner is settled by the caller before this runs, so nothing here touches them.
    func handleQueryExecutionError(
        _ error: Error,
        sql: String,
        tabId: UUID,
        connection conn: DatabaseConnection
    ) {
        let message = DatabaseWriteRejectionDiagnosis.formatted(error)
        helpersLogger.error(
            "Query failed on tab \(tabId, privacy: .public): \(error.localizedDescription, privacy: .public)"
        )
        parent.tabManager.mutate(tabId: tabId) { tab in
            tab.execution.errorMessage = message
            tab.execution.errorQuery = sql
            tab.execution.lastExecutedAt = Date()
            tab.execution.executionTime = nil
            tab.pagination.isLoading = false

            // The banner lives at the top of the results pane, so a collapsed pane hides the only
            // thing telling the user their query failed. Every success path opens it the same way.
            if tab.display.isResultsCollapsed {
                tab.display.isResultsCollapsed = false
            }
        }
        // The toolbar mirrors the selected tab, so a failure on a tab in the background describes
        // itself on its own tab and leaves the window chrome to whatever is actually on screen.
        if parent.tabManager.selectedTabId == tabId {
            parent.toolbarState.isResultsCollapsed = false
            parent.toolbarState.lastQueryDuration = nil
            parent.announceQueryError(message)
        }

        recordHistory(
            QueryHistoryRecordRequest(
                query: sql,
                connectionId: conn.id,
                databaseName: historyDatabaseName(tabId: tabId),
                databaseType: conn.type,
                schemaName: historySchemaName(tabId: tabId),
                source: historySource(tabId: tabId),
                executionTime: 0,
                rowCount: -1,
                wasSuccessful: false,
                errorMessage: error.localizedDescription
            )
        )
    }
}

enum RowCountPlan: Equatable {
    case skip
    case clear
    case approximate
    case exactCount(filtered: Bool)
    case filteredNonSQL(filters: [TableFilter], logicMode: FilterLogicMode)
}

enum RowCountOutcome: Equatable {
    case count(Int, isApproximate: Bool)
    case clear

    /// An estimate of zero or less means "unknown", never "this table is empty": an un-analyzed
    /// table reports 0 or -1 while holding millions of rows. An exact zero is trustworthy.
    ///
    /// Returns nil for "no answer", which is not the same as an answer of nothing. Phase 1 has
    /// usually already put an estimate on screen by the time this lands, so an unusable estimate
    /// must leave that alone rather than blank it. Only `.clear` means the count is genuinely
    /// gone, which is what a filter change asks for.
    var appliedTotal: (total: Int?, isApproximate: Bool)? {
        switch self {
        case .clear:
            return (nil, false)
        case let .count(value, isApproximate):
            guard value > 0 || (value == 0 && !isApproximate) else { return nil }
            return (value, isApproximate)
        }
    }
}
